version: '3'

networks:
    dockernet:
      external: true
services:
  user-service:
    environment:
      TOKEN_EXPIRATION: $TOKEN_EXPIRATION
      TOKEN_SECRET: $TOKEN_SECRET
      AUTHY_API_KEY: $AUTHY_API_KEY
      SPRING_JPA_SHOW_SQL: $SPRING_JPA_SHOW_SQL
      SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS: $SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS
      SPRING_PROFILES_ACTIVE: $SPRING_PROFILES_ACTIVE
      SPRING_DATASOURCE_URL: $USER_DB_URL
      SPRING_DATASOURCE_USERNAME: $USER_DB_USERNAME
      SPRING_DATASOURCE_PASSWORD: $USER_DB_PASSWORD
      SERVER_PORT: $USER_SERVICE_SERVER_PORT
      SERVER_SERVLET_CONTEXT_PATH: $USER_SERVICE_SERVLET_CONTEXT_PATH
      SPRING_CLOUD_STREAM_BINDINGS_USER_BINDER: $USER_SERVICE_KAFKA_BINDER
      SPRING_CLOUD_STREAM_BINDINGS_USER_DESTINATION: $USER_SERVICE_KAFKA_DESTINATION
      SPRING_CLOUD_STREAM_BINDINGS_USER_CONTENTTYPE: $USER_SERVICE_KAFKA_CONTENTTYPE
      SPRING_CLOUD_STREAM_BINDINGS_USER_GROUP: $USER_SERVICE_KAFKA_GROUP
      SPRING_CLOUD_STREAM_BINDINGS_USER_PRODUCER_REQUIREDGROUPS: $USER_SERVICE_KAFKA_PRODUCER_REQUIREDGROUPS
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: $USER_SERVICE_KAFKA_BROKERS
      SPRING_CLOUD_STREAM_KAFKA_BINDER_DEFAULT_BROKER_PORT: $USER_SERVICE_KAFKA_DEFAULT_BROKER_PORT
      SPRING_CLOUD_STREAM_KAFKA_BINDER_DEFAULT_ZK_PORT: $USER_SERVICE_KAFKA_DEFAULT_ZK_PORT
      SWAGGER_HOST: $SWAGGER_HOST
    build:
      context: ./user-service
      dockerfile: Dockerfile
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  user-db:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: $USER_DB_PASSWORD
    ports:
      - 5434:5432
    restart: always
    volumes:
      - ./db/postgres/user/data:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    restart: always

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 32181:32181
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
