const PHONE_CHECK_STEP: number = 1
const REGISTRATION_STEP: number = 2
const CONGRATULATIONS_STEP: number = 3
const AUTHENTICATE_STEP: number = 4

export default {
    PHONE_CHECK_STEP,
    REGISTRATION_STEP,
    CONGRATULATIONS_STEP,
    AUTHENTICATE_STEP
}